### ISSUE TITLE
Metrics to provide

### ISSUE THREAD

**Issue by aexvir** [okrahealth/okra#1]
* [x] Total number of files
* [x] Total number of contributors
* [ ] "Truck factor" number of contributors (active ones)
* [ ] Number of contributions within each period we care about
  * 30 days
  * 90 days
  * 360 days
* [ ] ~Number of downloads from PyPI~ It's not trivial
* [x] First commit date
* [x] Last commit date
* [x] Last commit hash

**Comment by tbonza** [comment]
#14 supersedes #1
