### ISSUE TITLE
Subset of metrics

### ISSUE THREAD

**Issue by treble37** [okrahealth/okra#11]
This is a "getting started" issue to make sure I'm on the right track that I'm creating for myself. So I'll only tackle 2 metrics issues from https://github.com/okrahealth/okra/issues/1:

- [x] Total number of files
- [x] Total number of contributors

**Comment by tbonza** [comment]
Looks good to me

**Comment by tbonza** [comment]
Interested to see if there’s a way to exclude files which are unrelated to actual code being written. Examples include documentation, configuration, and automatically generated files

**Comment by treble37** [comment]
Hmm....can/should we store a "file extension" column in meta to exclude all non ".py" extensions?  Not sure if that will work....

**Comment by tbonza** [comment]
Yeah that’s an option. Although we’d still pick up configuration files from Django, etc. Trying to think of a way which requires less subject matter expertise. 


Found the paper: https://dl.acm.org/citation.cfm?doid=3152284.3133908&preflayout=flat


Let’s get the other issues closed then come back to this. One of their key takeaways was finding about 70% of code on GitHub to be duplicated

**Comment by treble37** [comment]
Merged...
